[package]
name = "maps-download-check"
version = "0.1.0"
authors = ["Paco van der Linden <pavadeli@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3.14", features = [ "paw" ] }
paw = "1.0.0"
